#!/bin/bash
# 2010-07-24

# top-level folders to exclude
EXCLUDE='launchers|misc|setup'

IFS=$'\n'

exec >&2
declare -i code=0

# no action
if [ "$1" = "-n" ]; then
	dry_run=echo
else
	dry_run=
fi

recurse() {
	local wd="$PWD" file target

	for file in *
	do
		if	[[ -z "$1" && "$file" =~ ^("$this"|$EXCLUDE)$ ]]; then
			continue
		fi
		target="${1:-$HOME/.}$file"

		if [[ "$file" =~ [*?] ]]
		then
			glob=$(ls -d $target 2>/dev/null)
			if [[ $? -ne 0 || ! -e "$glob" ]]; then
				echo "No match: $target"
				code+=1
				continue
			else
				target="$glob"
			fi
		fi

		if [ -h "$target" ]
		then
			# silently re-link matching or non-existent symlinks
			if   [[ -d "$file" && -d "$target" ]]
			then
				$dry_run ln -sfT "$wd/$file" "$target"

			elif [[ -f "$file" && -f "$target" || ! -e "$target" ]]
			then
				$dry_run ln -sf  "$wd/$file" "$target"
			else
				! echo "File-directory mismatch: $target"
			fi

		elif [ -d "$target" ]
		then
			# recurse if directory
			if [ -d "$file" ]
			then
				if ! cd "$file"; then
					false
				else
					# append a level
					recurse "$target/"
					cd "$wd"
				fi
			else
				! echo "File-directory mismatch: $target"
			fi

		elif [ -e "$target" ]
		then
			# replace existing file?
			ls -lh "$target"
			echo -n "Remove and link? [y/N] " && read
			if [[ "$REPLY" == [Yy]* ]]; then
				$dry_run ln -sf "$wd/$file" "$target"
			else
				continue
			fi

		else
			# new link
			$dry_run ln -s "$wd/$file" "$target"
		fi

		code+=$?
	done
}

path=$(readlink -e -- "$(which "$0")")
this=$(basename -- "$path")

cd "${path%$this}"

recurse
exit $code

