#!/bin/bash

####### Set $directory to target directory
IFS=$'\n'

if echo "$NAUTILUS_SCRIPT_CURRENT_URI" | grep -v '^file:' > /dev/null; then
	zenity --error --text="Not in a local directory."
	exit 1
fi

set $NAUTILUS_SCRIPT_SELECTED_FILE_PATHS

if [ $# -ne 1 ]; then
	directory="$PWD"
elif [ -d "$1" ]; then
	directory="$1"
else
	directory=$(dirname "$1")
fi
#directory=$(echo "$directory" | sed 's/ /\\ /g')
#######

cd "$directory"
exec gnome-search-tool
