#!/bin/bash

OPEN=( Thunar 'nautilus --no-desktop' )
FILE=( exo-open gnome-open )

if [[ -d "$1" || "$1" =~ (:|/)$ ]]; then
	:

elif [ -f "$1" ]; then
	OPEN=( "${FILE[@]}" )

elif [ $# -gt 0 ]; then
	[ "$1" = "--dir" ] && shift
	set -- "$(dirname -- "$1")" "${@:2}"

else
	set -- "$PWD"

fi


for cmd in "${OPEN[@]}"; do
	if type "${cmd%% *}" &>/dev/null; then
		$cmd "$@" &>/dev/null
		exit
	fi
done

exit 1
