#!/bin/bash

FILE="$HOME/.dmenu"
DMENU=$(cat "$FILE") || exit 2
CHOICES=$(echo "$DMENU" | grep -v '^#' | perl -pe 's/\S+\t//')

OPTS=( -b -nb '#8c8c88' -nf black -sb '#c7c7c4' -sf black
       -fn '-*-andale mono-medium-r-normal-*-17-*-100-100-*-*-*-*' )

choice=$(echo "$CHOICES" | dmenu "${OPTS[@]}") || exit $?

if [[ "$choice" =~ ^[^[:alnum:]] ]]; then
	# bring up the system-wide dmenu on non-alphanumeric input
    dmenu_run "${OPTS[@]}"
    exit
else
    command $choice
	code=$?
fi

echo "$DMENU" | perl -e '
$found = 0;
$choice = qq('"$choice"');
while (<>) {
    chomp;
    @fields = split(/\t/);
    if (scalar(@fields) != 2) {
        next;
    } elsif ($choice eq $fields[1] || $choice =~ m/^$fields[1]\s*\b/) {
        $_  = ++$fields[0] . "\t" . $fields[1];
		$found = 1;
    }
} continue {
    push(@lines, "$_$/");
}
if (! $found && $choice =~ m/^[\w-]+$/
	&& system("which " . $choice . " &>/dev/null") == 0) {
	push(@lines, "1\t" . $choice . "$/");
}
@sorted = map  { $_->[0] }
          sort { $b->[1] <=> $a->[1] }
          map  { [ $_, ($_ =~ m/^(\d+)/)[0] ] }
          @lines;
print @sorted;' >"$FILE"

exit $code
