#!/bin/bash

# preferred terminals, in order
TERMINALS=(
	# terminal-command directory-option execute-option
	'Terminal --working-directory -x'
	'urxvt -cd -e'
	'gnome-terminal --working-directory -x'
)

for arg in "$@"; do
	if [[ "$arg" =~ ^-[?] ]]; then
		echo "Usage: $(basename "$0") [1-9] [dir|file] [opts|cmd]"
		exit
	fi
done

if [[ ! -e "$1" && "$1" == [1-9] ]]
then count=$1 && shift
else count=1
fi

# "manual" home directory globbing
if [ $# -gt 0 ]; then
	dir="${1/#\$HOME\//$HOME/}" && shift
	dir="${dir/#\~\//$HOME/}"
	set -- "$dir" "$@"
fi

# get working directory
if [[ -d "$1" || "$1" == /* || "$1" == */ ]]; then
	dir="$1"
	shift
elif [ -e "$1" ]; then
	dir=$(dirname -- "$1")
	shift
else
	dir="$PWD"
fi
dir=$(readlink -m "$dir")

for terminal in "${TERMINALS[@]}"; do
	terminal=($terminal)
	if type "${terminal[0]}" &>/dev/null; then
		if [ $# -gt 0 ] && type "$1" &>/dev/null; then
			set -- "${terminal[2]}" "$@"
		fi
		for count in $(seq 1 $count); do
			# LANG="en_US.UTF-8" LC_ALL="en_US.UTF-8"
			"${terminal[0]}" "${terminal[1]}" "$dir" "$@"
		done
		exit
	fi
done

exit 1
