#!/bin/bash

[ ! -d "$LOGDIR" ] && LOGDIR="$HOME/doc/txt"

TODO="$LOGDIR/todo"

LOCK="$HOME/.$(basename -- "$0").lock"
unset TEMPFILE

if [ -e "$LOCK" -o ! -f "$TODO" -o ! -r "$TODO" ]; then
	exit 1
fi

cleanUp() {
	rm -f "$LOCK" "$TEMPFILE"
	exit $1
}
trap "cleanUp 1" 1 2 3 15

> "$LOCK"

#TEMPFILE=$(mktemp)
#
#zenity	--text-info --title="TODO" --height=724 --width=220 \
#		--filename="$TODO" --editable >"$TEMPFILE"
#
#if	[ $? -eq 0 ] &&
#	type trimfile &>/dev/null && trimfile "$TEMPFILE" &&
#	[ -s "$TEMPFILE" ] &&
#	! cmp -s "$TEMPFILE" "$TODO" &&
#	[ "$(head -n1 "$TEMPFILE")" = "#!log" ]
#then
#	cp "$TEMPFILE" "$TODO"
#fi

cd "$LOGDIR" &&
gvim -f	-U NONE	+'set columns=64 lines=47'	\
				+'set t_vb='				\
				+'tab ball'					\
				+'silent! tabdo %foldclose!'\
				+'tabn 1'					\
	"$TODO" "$LOGDIR"/{list,log}

cleanUp 0
