#!/bin/bash

IFS=$'\n'

add ()
{
	for pkg in "$@"; do
		list+=("$pkg")
	done
}

list=()

##1 UI
add dmenu
add gksu
add screen
add xbindkeys
add zenity
add zsh

##1 command-line
add bc
add expect
add fbida # image viewer
add lesspipe # input filter for less
add pinfo # alternate info viewer
add pv
add scrot
add units
add xclip
add xsel

##1 languages
add clisp
add ghc
add jre jdk
add lua luajit
add parrot
add perl
add php
add python
add python2
add ruby
add tcl tk

##2 perl
add gtk2-perl
add mod_perl
add perl-bit-vector
add perl-dbd-mysql
add perl-dbd-sqlite
add perl-exiftool
add perl-inline
add perl-mp3-info
add perl-term-readkey
add perl-term-readline
add perl-text-markdown
add perl-yaml-syck

##2 python
add python-fuse
add python-numpy
add python-pygame
add python-scipy
add python-simplejson
add python-webpy

##1 libraries/tools
add blueman
add boost
add gob2
add librsvg
# add mono
add openal
add pkgtools
add wine
add xdg-utils
add xorg-utils
add yajl

##1 services
add apache
add mysql
add php-apache
add postgresql

##1 development
add ctags
add gdb
add giggle
add git
add mercurial
add subversion
add wordpress

##2 editors
add emacs
add hexedit

##1 networking
add curl
add ettercap
add gnu-netcat
add ncftp
add nmap
add samba
add sshfs

##1 filesystem
add dosfstools
add gparted
add ntfs-3g
add ntfsprogs
add partimage
add sleuthkit
add testdisk

##1 files/documents
add fdupes # find duplicate files
add vifm

##2 text processing
add antiword
add libreoffice
add words

##2 compression
add p7zip
add unrar
add unzip
add xarchiver
add zip

##2 pdf/tex
# add gummi
# add lyx
add texinfo
add texlive-core

##1 security
add gnupg
add keepassx
add tor
add truecrypt

##1 web
# add filezilla
add firefox
add lynx
add uzbl-tabbed
add w3m

##2 email
# add mutt
add thunderbird

##2 chat
add irssi
add skype

##2 torrents
add mktorrent
add transmission-gtk # deluge

##1 graphics
##2 viewers
add gqview # geeqie
add qiv
# add comical

##2 editors
add gimp
add inkscape
add dia

##2 utils
add netpbm
add optipng

##1 multimedia
##2 audio
##3 players
add clementine
add cmus
add deadbeef
add gmpc # sonata
add mpd ncmpcpp # ncmpc mpc
add mpg123
add timidity++ # MIDI player

##3 editors
add audacity
add easytag
add mp3gain
add mp3info
add mp3splt
add sox

##2 video
##3 players
add vlc # mplayer
# add miro

##3 editors
# add handbrake
add avidemux-gtk

##2 codecs/plugins
add gstreamer0.10-plugins
add libdvdcss

add flashplugin

##2 peripherals
add gphoto2
add gtkpod

##2 optical
add cdrkit # includes mkisofs cdda2wav cdrecord etc.
add cdrdao # writing cue/bin files
# add cdemu-client # cue-bin emulation

##1 misc
add anki # supermemo alternative
add gourmet
# add lilypond # music notation
# add tuxguitar

##2 i18n
add gucharmap
add scim
add scim-pinyin scim-tables
add stardict

##2 math
add mathomatic

##2 games
add dosbox
# add dwarffortress
# add freeciv
# add nethack
# add wesnoth

##1 INSTALL
[ $(whoami) = root ] && exit 1

sudo pacman -Sy --needed "${list[@]}"

##1 REPLACE PACKAGES
list=()
add fam

sudo pacman -Rdsn "${list[@]}"

list=()
add gamin

sudo pacman -S --needed "${list[@]}"

##1 vim:set ts=4 sw=4 noet fdm=marker fmr=##,##:
