#!/bin/bash

PFLAGS="--needed --noconfirm"

add ()
{
	for pkg in "$@"; do
		list+=("$pkg")
	done
}

[ $(whoami) = root ] && exit 1

echo "Installing X ..." ##1

# libraries
list=()
add libgl

sudo pacman -Sy $PFLAGS "${list[@]}"

# X
list=()
add xf86-input-evdev
add xf86-input-keyboard
add xf86-input-mouse
add xf86-input-synaptics
add xf86-video-ati
add xf86-video-vesa
add xorg-fonts-100dpi xorg-fonts-75dpi
add xorg-res-utils
add xorg-server
add xorg-twm
add xorg-xinit
add xterm
add mesa

sudo pacman -S $PFLAGS "${list[@]}"

echo "Installing Xfce ..." ##1

##2 xfce4
list=()
add gtk-xfce-engine
add terminal
add thunar
add xfconf xfdesktop xfprint
add xfce-utils
# add xfce4-appfinder
# add xfce4-icon-theme
add xfce4-mixer
add xfce4-panel
add xfce4-session
add xfce4-settings
add xfwm4 # xfwm4-themes

sudo pacman -S $PFLAGS "${list[@]}"

##2 xfce4-goodies
list=()
add thunar-archive-plugin thunar-volman thunar-media-tags-plugin
add verve-plugin
add xfce4-dev-tools
add xfce4-notifyd
add xfce4-power-manager
add xfce4-screenshooter
add xfce4-taskmanager

##2 panel plugins
add xfce4-battery-plugin
add xfce4-clipman-plugin
add xfce4-cpufreq-plugin
add xfce4-cpugraph-plugin
add xfce4-datetime-plugin
add xfce4-diskperf-plugin
add xfce4-fsguard-plugin
add xfce4-genmon-plugin
add xfce4-mailwatch-plugin
add xfce4-messenger-plugin
add xfce4-mount-plugin
add xfce4-mpc-plugin
add xfce4-netload-plugin
add xfce4-notes-plugin
# add xfce4-playercontrol-plugin
add xfce4-sensors-plugin
# add xfce4-smartbookmark-plugin
add xfce4-systemload-plugin
# add xfce4-timer-plugin
# add xfce4-wavelan-plugin
# add xfce4-weather-plugin
# add xfce4-xfapplet-plugin
add xfce4-xkb-plugin

sudo pacman -S $PFLAGS "${list[@]}"

echo "Installing the rest ..." ##1
list=()

# login manager
add slim

# utils
add blueman
add slock

# fonts
add ttf-bitstream-vera
add ttf-dejavu
add ttf-junicode
# add ttf-ms-fonts
# CJK
add ttf-arphic-uming ttf-arphic-ukai ttf-fireflysung
add wqy-zenhei wqy-bitmapfont

# apps
add gvim
add firefox

sudo pacman -S $PFLAGS "${list[@]}"

##1 vim:set ts=4 sw=4 noet fdm=marker fmr=##,##:
