#!/bin/bash

IFS=$'\n'

add ()
{
	for pkg in "$@"; do
		list+=("$pkg")
	done
}

list=()

add cpufrequtils
add tpb
add wicd
# add laptop-mode-tools

[ $(whoami) = root ] && exit 1

sudo pacman -Sy --needed "${list[@]}"
