#!/bin/bash

IFS=$'\n'

add ()
{
	for pkg in "$@"; do
		list+=("$pkg")
	done
}

list=()

[ $(whoami) = root ] && exit 1

##1 yaourt
if false; then
	echo -n "Install yaourt? [Y/n] "
	read reply
	if [[ "$reply" == [Nn]* ]]; then
		exit 0
	fi

	TMP=~/tmp
	YAOURT=yaourt.tar.gz

	if [ ! -d $TMP ]; then
		mkdir -p $TMP
	fi
	cd $TMP && \
		wget http://aur.archlinux.org/packages/yaourt/$YAOURT && \
		tar xzvf $YAOURT && rm $YAOURT && cd yaourt && \
		vi PKGBUILD yaourt.install

	echo -n "Make package and install? [y/N] "
	read reply
	if [[ "$reply" == [Yy]* ]]; then
		makepkg PKGBUILD && sudo pacman -U yaourt-*.pkg.tar.gz
	fi

	rm -rf $TMP/yaourt
	[ -z "$(ls -A $TMP)" ] && rmdir $TMP
fi

add aurvote

##1 UI
add xautomation

##1 command-line
add ack # grep drop-in
add ascii
add trash-cli

##1 languages
add mit-scheme

##1 libraries
add libsvg

##1 filesystem
add foremost # file recovery tool

##1 files & documents
add detox # clean up filenames
add vifm

##2 pdf & tex
add evince-gtk
# add gummi
add pdftk

##1 web
add uzbl-git

##1 graphics
add svg2png

##1 multimedia
##2 audio
add clementine
# add deadbeef
add fluidr3 # MIDI soundfont

##2 video
# add winff

##2 optical
# add cdrtools # alternative to cdrkit

##1 misc
add mbrola # text-to-speech

##2 i18n
add stardict-i2e-es-en
add stardict-oald

##1 INSTALL
if which yaourt &>/dev/null; then
	for pkg in "${list[@]}"; do
		echo -n "Download, make, and install $pkg? [Y/n] "
		read reply
		if [[ "$reply" != [Nn]* ]]; then
			yaourt -S --needed --noconfirm $pkg
		fi
	done
else
	! echo >&2 "Please install yaourt first."
fi

##1 vim:set ts=4 sw=4 noet fdm=marker fmr=##,##:
