#!/bin/bash

IFS=$'\n'

add ()
{
	for pkg in "$@"; do
		list+=("$pkg")
	done
}

list=()

[ $(whoami) = root ] && exit 1

##1 yaourt
echodo () { echo "$@" && "$@"; }

aur ()
{
	echo -n "Install $1? [Y/n] "
	read reply
	if [[ "$reply" == [Nn]* ]]; then
		return 0
	fi

	URL="$2"
	PKG=$(echo "$URL" | sed 's|^.*/||')
	cd $TMP && \
		# wget tarball
		echodo wget "$URL" && \
		echodo tar xvf $PKG && rm $PKG && \
		cd $1
	[ $? -ne 0 ] && return 1

	echo -n "Make package and install? [Y/n] "
	read reply
	if [[ "$reply" != [Nn]* ]]; then
		# make and install
		echodo makepkg PKGBUILD && echodo sudo pacman -U $1-*.pkg.tar.?z
		[ $? -ne 0 ] && return 1
	fi
	rm -rf $TMP/$1
}

if ! which yaourt &>/dev/null; then
	TMP=~/tmp
	if [ ! -d $TMP ]; then
		mkdir -p $TMP
	fi
	aur package-query http://aur.archlinux.org/packages/package-query/package-query.tar.gz || exit 1
	aur yaourt        http://aur.archlinux.org/packages/yaourt/yaourt.tar.gz               || exit 1
	[ -z "$(ls -A $TMP)" ] && rmdir $TMP
fi

add aurvote

##1 UI
add xautomation

##1 fonts
add ttf-google-webfonts
add ttf-ms-fonts
add ttf-tahoma
# add ttf-vista-fonts

##1 command-line
add ack # grep drop-in
add ascii
add trash-cli

##1 languages
add mit-scheme

##1 libraries/tools
# add thunar-vcs-plugin

##1 filesystem
add foremost # file recovery tool

##1 files/documents
add detox # clean up filenames

##2 pdf/tex

##1 graphics
add gimp-resynth
add libsvg
add svg2png

##1 multimedia
##2 audio
add fluidr3 # MIDI soundfont
add flac2mp3

##2 video
# add winff

##2 optical
# add cdrtools # alternative to cdrkit

##1 misc
# add brainworkshop
add galculator
add mbrola # text-to-speech

##1 INSTALL
if which clyde &>/dev/null; then
	AUR=(sudo clyde)
elif which yaourt &>/dev/null; then
	AUR=(yaourt)
else
	echo >&2 "No AUR frontend found."
	exit 1
fi

for pkg in "${list[@]}"; do
	echo -n "Download, make, and install $pkg? [Y/n] "
	read reply
	if [[ "$reply" != [Nn]* ]]; then
		"${AUR[@]}" -S --noconfirm $pkg
	fi
done

##1 vim:set ts=4 sw=4 noet fdm=marker fmr=##,##:
