#!/bin/bash

IFS=$'\n'

add ()
{
	for pkg in "$@"; do
		list+=("$pkg")
	done
}

list=()

add xf86-video-ati
add xf86-input-synaptics

add cpufrequtils
add wicd
add tpb
add laptop-mode-tools

[ $(whoami) = root ] && exit 1

sudo pacman -Sy --needed "${list[@]}"
