#!/bin/bash

IFS=$'\n'

add ()
{
	for pkg in "$@"; do
		list+=("$pkg")
	done
}

list=()

##1 UI
# add dmenu
add expect
add gksu
# add launchy
add screen
add xbindkeys
add zenity

##1 shells
# add rxvt-unicode-256color
add zsh

##2 command-line utils
add bc
add lesspipe # input filter for less
add pinfo # alternate info viewer
add pkgtools
add pv
# add scrot
add units
add xclip

##1 languages
add clisp
add ghc
add jre jdk
add lua luajit
add parrot
add perl
add php
add python
add python3
add ruby
add tcl tk

##2 perl
add mod_perl
add perl-bit-vector
add perl-dbd-mysql
add perl-dbd-sqlite
add perl-exiftool
add perl-inline
add perl-mp3-info
add perl-term-readkey
add perl-term-readline
add perl-text-markdown
add perl-yaml-syck
add perlxml

##2 python
add python-simplejson
add python-webpy

##1 libraries
add boost
add gob2
add librsvg
add mono
add wine
add xdg-utils
add xorg-utils

##1 development
add ctags
add gdb
add git
add subversion

##2 editors
add emacs
add hexedit

##1 networking
add curl
add ettercap
add gnu-netcat
add ncftp
add nmap
add samba
add sshfs

##1 filesystem
add dosfstools
add gparted
add ntfs-3g
add ntfsprogs
add partimage
add sleuthkit
add testdisk

##1 files & documents
add fdupes # find duplicate files
add openoffice-base
add words

##2 compression
add p7zip
add unzip
add xarchiver
add zip

##2 privacy
add gnupg
add tor
add truecrypt

##2 pdf & tex
add epdfview
add texlive-core
add texinfo

##1 web
add lynx
add w3m

##2 email
add thunderbird
# add mutt

##2 chat
add irssi
add skype

##2 torrents
add transmission-gtk # deluge
add mktorrent

##1 graphics
##2 viewers
add gqview # geeqie
add mirage
# add comical
add gphoto2 gtkam

##2 editors
add gimp
add inkscape
add dia

##2 utils
add netpbm
add optipng

##1 multimedia
##2 audio
##3 players
add mpg123
add mpd ncmpcpp # ncmpc mpc
add gmpc # sonata
# add cmus
add xfmedia # banshee
add timidity++ # MIDI player

##3 editors
add audacity
add easytag
add mp3gain
add mp3info
add mp3splt
add sox

##2 video
##3 players
add vlc # mplayer
# add miro

##3 editors
add handbrake

##2 codecs
add flashplugin
add gstreamer0.10-plugins
add libdvdcss

##2 interface
add gtkpod

##2 optical
add cdrkit # includes mkisofs cdda2wav cdrecord etc.
add cdrdao # for writing cue/bin files
# add cdemu-client # for cue-bin emulation
add xfburn

##1 special
add anki # supermemo alternative
# add gourmet
add pokerth

##2 i18n
add gucharmap
add scim
add scim-pinyin scim-tables
add stardict

##2 math
add galculator # gcalctool
add mathomatic

##1 INSTALL
[ $(whoami) = root ] && exit 1

sudo pacman -Sy --needed "${list[@]}"

##1 REPLACE PACKAGES
list=()
add fam

sudo pacman -Rdsn --noconfirm "${list[@]}"

list=()
add gamin

sudo pacman -S --needed --noconfirm "${list[@]}"

##1 vim:set ts=4 sw=4 noet fdm=marker fmr=##,##:
