#!/bin/bash

IFS=$'\n'

add ()
{
	for pkg in "$@"; do
		list+=("$pkg")
	done
}

list=()

## shells
add zsh

## languages
add parrot
add perl
add python
add python3
add lua luajit
add tcl tk
add clisp
add ghc
add ruby
add php
add jre jdk

add mod_perl
add perl-bit-vector
add perl-dbd-mysql
add perl-dbd-sqlite
add perl-inline
add perl-mp3-info
add perl-term-readkey
add perl-term-readline
add perl-text-markdown
add perl-yaml-syck
add perlxml

add python-simplejson
add python-webpy

## editors
add emacs
add hexedit

## development
add gdb
add ctags
add git
add subversion

## libraries
add mono
add boost
add gob2
add librsvg

## networking
add curl
add ettercap
add gnu-netcat
add ncftp
add nmap
add samba
add sshfs

## system
add dosfstools
add gparted
add ntfs-3g
add ntfsprogs
add sleuthkit
add testdisk

## utils
add bc
# add dmenu
add expect
add fdupes # find duplicate files
add galculator gcalctool
add gksu
add gnupg
add lesspipe
add mathomatic
add partimage
add pinfo # alternate info viewer
add pkgtools
add pv
# add rxvt-unicode-256color
add screen
# add scrot
add units
add wine
add xbindkeys
add xclip
add xdg-utils
add xorg-utils
add zenity

## compression
add unzip
add p7zip
add xarchiver
add zip

# input
add gucharmap
add scim
add scim-pinyin scim-tables
add stardict

## office
add epdfview
add openoffice-base
add thunderbird
# add mutt
add words

# internet
add irssi
add lynx
add skype
add transmission-gtk # deluge
add mktorrent
add w3m

## graphics and photos
add netpbm
add optipng
add gqview mirage
add gimp
add inkscape
add dia # diagramming tool
add gphoto2 gtkam
# add comical # comic book reader

## codecs
add gstreamer0.10-plugins
add libdvdcss
add flashplugin

## multimedia
add mpg123
add mpd ncmpcpp # ncmpc mpc
add gmpc # sonata
# add cmus
add xfmedia banshee
add timidity++ # MIDI player
add gtkpod

add audacity
add easytag
add mp3gain
add mp3info
add mp3splt
add sox

add vlc miro # mplayer

## disk burning
add cdrkit # includes mkisofs cdda2wav cdrecord etc.
add cdrdao # for writing cue/bin files
# add cdemu-client # for cue-bin emulation
add xfburn

## misc
# add gourmet

[ $(whoami) = root ] && exit 1

sudo pacman -Sy --needed "${list[@]}"

## replacement packages
list=()

add fam

sudo pacman -Rdsn --noconfirm "${list[@]}"

list=()

add gamin

sudo pacman -S --needed --noconfirm "${list[@]}"
